checkupdates: Fix indentation
Signed-off-by: Johannes Löthberg <johannes@kyriasis.com>

diff --git a/src/checkupdates.sh.in b/src/checkupdates.sh.in
--- a/src/checkupdates.sh.in
+++ b/src/checkupdates.sh.in
@@ -86,8 +86,8 @@ fi
 mkdir -p "$CHECKUPDATES_DB"
 ln -s "${DBPath}/local" "$CHECKUPDATES_DB" &> /dev/null
 if ! fakeroot -- pacman -Sy --dbpath "$CHECKUPDATES_DB" --logfile /dev/null &> /dev/null; then
-       error 'Cannot fetch updates'
-       exit 1
+	error 'Cannot fetch updates'
+	exit 1
 fi
 mapfile -t updates < <(pacman -Qu --dbpath "$CHECKUPDATES_DB" 2> /dev/null | grep -v '\[.*\]')
 
