checkupdates: report failure to fetch updates
Exit the script with 1 if pacman -Sy call failed. This would let a user
to distinguish whether there're no updates or pacman failed to fetch
them.

Fixes FS#55206

Signed-off-by: Andrew Barchuk <andrew@raindev.io>
Message-Id: <1503345938.476708.1080452304.09FD1100@webmail.messagingengine.com>

diff --git a/src/checkupdates.sh.in b/src/checkupdates.sh.in
--- a/src/checkupdates.sh.in
+++ b/src/checkupdates.sh.in
@@ -53,7 +53,10 @@ fi
 
 mkdir -p "$CHECKUPDATES_DB"
 ln -s "${DBPath}/local" "$CHECKUPDATES_DB" &> /dev/null
-fakeroot -- pacman -Sy --dbpath "$CHECKUPDATES_DB" --logfile /dev/null &> /dev/null
+if ! fakeroot -- pacman -Sy --dbpath "$CHECKUPDATES_DB" --logfile /dev/null &> /dev/null; then
+       error 'Cannot fetch updates'
+       exit 1
+fi
 pacman -Qu --dbpath "$CHECKUPDATES_DB" 2> /dev/null | grep -v '\[.*\]'
 
 exit 0
